export const TYPES_SEARCH = [
  { value: 'accounting', name: 'contabilidade' },
  { value: 'airport', name: 'aeroporto'},
  { value: 'amusement_park', name: 'Parque de diversões' },
  { value: 'aquarium', name: 'aquário'},
  { value: 'art_gallery', name : 'galeria de Arte'},
  { value: 'atm', name: 'ATM'},
  { value: 'bakery', name: 'padaria'},
  { value: 'bank', name: 'banco'},
  { value: 'bar', name: 'Bar'},
  { value: 'beauty_salon', name: 'salão de beleza'},
  { value: 'bicycle_store', name: 'Loja de bicicletas'},
  { value: 'book_store', name: 'livraria'},
  { value: 'bowling_alley', name: 'Pista de boliche'},
  { value: 'bus_station', name: 'estação de onibus'},
  { value: 'cafe', name: 'lanchonete'},
  { value: 'campground', name: 'área de camping'},
  { value: 'car_dealer', name: 'venda de carros'},
  { value: 'car_rental', name: 'Aluguel de carro'},
  { value: 'car_repair', name: 'reparo de carro'},
  { value: 'car_wash', name: 'lava-jato'},
  { value: 'casino', name: 'casino'},
  { value: 'cemetery', name: 'cemitério'},
  { value: 'church', name: 'Igreja'},
  { value: 'city_hall', name: 'Prefeitura'},
  { value: 'clothing_store', name: 'loja de roupas'},
  { value: 'convenience_store', name: 'loja de conveniência'},
  { value: 'courthouse', name: 'Tribunal'},
  { value: 'dentist', name: 'dentista'},
  { value: 'department_store', name: 'loja de departamento'},
  { value: 'doctor', name: 'médico'},
  { value: 'electrician', name: 'eletricista'},
  { value: 'electronics_store', name: 'loja de eletrônicos'},
  { value: 'embassy', name: 'embaixada'},
  { value: 'fire_station', name: 'Corpo de Bombeiros'},
  { value: 'florist', name: 'florista'},
  { value: 'funeral_home', name: 'Casa funerária'},
  { value: 'furniture_store', name: 'loja de móveis'},
  { value: 'gas_station', name: 'posto de gasolina'},
  { value: 'grocery_or_supermarket', name: 'Supermercado'},
  { value: 'gym', name: 'Academia'},
  { value: 'hair_care', name: 'cuidado capilar'},
  { value: 'hardware_store', name: 'Loja de ferragens'},
  { value: 'health', name: 'saúde'},
  { value: 'hindu_temple', name: 'Templo hindu'},
  { value: 'home_goods_store', name: 'Loja de artigos para o lar'},
  { value: 'hospital', name: 'hospital'},
  { value: 'insurance_agency', name: 'agência de seguros'},
  { value: 'jewelry_store', name: 'Loja de jóias'},
  { value: 'laundry', name: 'lavanderia'},
  { value: 'lawyer', name: 'advogado'},
  { value: 'library', name: 'biblioteca'},
  { value: 'liquor_store', name: 'Loja de bebidas alcoólicas'},
  { value: 'local_government_office', name: 'Escritório do governo local'},
  { value: 'locksmith', name: 'chaveiro'},
  { value: 'lodging', name: 'alojamento'},
  { value: 'movie_theater', name: 'cinema'},
  { value: 'moving_company', name: 'Empresa de mudanças'},
  { value: 'museum', name: 'museum'},
  { value: 'night_club', name: 'Boate'},
  { value: 'park', name: 'parque'},
  { value: 'parking', name: 'estacionamento'},
  { value: 'pet_store', name: 'loja de animais'},
  { value: 'pharmacy', name: 'farmacia'},
  { value: 'physiotherapist', name: 'fisioterapeuta'},
  { value: 'plumber', name: 'encanador'},
  { value: 'police', name: 'polícia'},
  { value: 'post_office', name: 'Agência dos Correios'},
  { value: 'real_estate_agency', name: 'Agência imobiliária'},
  { value: 'restaurant', name: 'restaurante'},
  { value: 'school', name: 'escola'},
  { value: 'shoe_store', name: 'loja de sapatos'},
  { value: 'shopping_mall', name: 'Centro de compras'},
  { value: 'spa', name: 'spa'},
  { value: 'stadium', name: 'estádio'},
  { value: 'storage', name: 'armazenamento'},
  { value: 'store', name: 'loja'},
  { value: 'subway_station', name: 'estação de metrô'},
  { value: 'taxi_stand', name: 'ponto de taxi'},
  { value: 'train_station', name: 'estação de trem'},
  { value: 'travel_agency', name: 'agência de viagens'},
  { value: 'university', name: 'universidade'},
  { value: 'veterinary_care', name: 'veterinário'},
  { value: 'zoo', name: 'jardim zoológico'}
];
